export { default as Hero } from './Hero'
export { default as HowItWorks } from './HowItWorks'
export { default as TrainersHub } from './TrainersHub'
export { default as Payment } from './Payment'
export { default as FAQ } from './FAQ'
